import { arguments_assert } from '../arguments/assert.mjs';
import { metadata } from '../metadata.mjs';
import { comment } from '../comment.mjs';
import { noop } from '../noop.mjs';
comment(`This metadata means the code was autogenerated and should not be changed by hand`);
export function metadata_generated() {
    arguments_assert(arguments, []);
    noop();
    metadata([]);
}