import { log } from './log.mjs';
import { string_sub_test_generated_9 } from './string/sub/test/generated/9.mjs';
import { string_sub_test_generated_8 } from './string/sub/test/generated/8.mjs';
import { string_sub_test_generated_7 } from './string/sub/test/generated/7.mjs';
import { string_sub_test_generated_6 } from './string/sub/test/generated/6.mjs';
import { string_sub_test_generated_5 } from './string/sub/test/generated/5.mjs';
import { string_sub_test_generated_4 } from './string/sub/test/generated/4.mjs';
import { string_sub_test_generated_3 } from './string/sub/test/generated/3.mjs';
import { string_sub_test_generated_2 } from './string/sub/test/generated/2.mjs';
import { string_sub_test_generated_10 } from './string/sub/test/generated/10.mjs';
import { string_sub_test_generated_1 } from './string/sub/test/generated/1.mjs';
import { string_is_test_values } from './string/is/test/values.mjs';
import { integer_is_test_values } from './integer/is/test/values.mjs';
import { error_test_3 } from './error/test/3.mjs';
import { error_test_2 } from './error/test/2.mjs';
import { error_test_1 } from './error/test/1.mjs';
import { comment_test_3 } from './comment/test/3.mjs';
import { comment_test_2 } from './comment/test/2.mjs';
import { comment_test_1 } from './comment/test/1.mjs';
import { assert_test_5 } from './assert/test/5.mjs';
import { assert_test_4 } from './assert/test/4.mjs';
import { assert_test_3 } from './assert/test/3.mjs';
import { assert_test_2 } from './assert/test/2.mjs';
import { assert_test_1 } from './assert/test/1.mjs';
import { arguments_count_test_5 } from './arguments/count/test/5.mjs';
import { arguments_count_test_4 } from './arguments/count/test/4.mjs';
import { arguments_count_test_3 } from './arguments/count/test/3.mjs';
import { arguments_count_test_2 } from './arguments/count/test/2.mjs';
import { arguments_count_test_1 } from './arguments/count/test/1.mjs';
import { arguments_assert_test_4 } from './arguments/assert/test/4.mjs';
import { arguments_assert_test_3 } from './arguments/assert/test/3.mjs';
import { arguments_assert_test_2 } from './arguments/assert/test/2.mjs';
import { arguments_assert_test_1 } from './arguments/assert/test/1.mjs';
import { add_1_test_6 } from './add/1/test/6.mjs';
import { add_1_test_5 } from './add/1/test/5.mjs';
import { add_1_test_4 } from './add/1/test/4.mjs';
import { add_1_test_3 } from './add/1/test/3.mjs';
import { add_1_test_2 } from './add/1/test/2.mjs';
import { add_1_test_1 } from './add/1/test/1.mjs';
export async function tests() {
    await add_1_test_1();
    await add_1_test_2();
    await add_1_test_3();
    await add_1_test_4();
    await add_1_test_5();
    await add_1_test_6();
    await arguments_assert_test_1();
    await arguments_assert_test_2();
    await arguments_assert_test_3();
    await arguments_assert_test_4();
    await arguments_count_test_1();
    await arguments_count_test_2();
    await arguments_count_test_3();
    await arguments_count_test_4();
    await arguments_count_test_5();
    await assert_test_1();
    await assert_test_2();
    await assert_test_3();
    await assert_test_4();
    await assert_test_5();
    await comment_test_1();
    await comment_test_2();
    await comment_test_3();
    await error_test_1();
    await error_test_2();
    await error_test_3();
    await integer_is_test_values();
    await string_is_test_values();
    await string_sub_test_generated_1();
    await string_sub_test_generated_10();
    await string_sub_test_generated_2();
    await string_sub_test_generated_3();
    await string_sub_test_generated_4();
    await string_sub_test_generated_5();
    await string_sub_test_generated_6();
    await string_sub_test_generated_7();
    await string_sub_test_generated_8();
    await string_sub_test_generated_9();
    log(38 + ' tests ran successfully');
}