import { metadata } from './metadata.mjs';
import { string_combine } from './string/combine.mjs';
import { log } from './log.mjs';
import { string_underscore_is_test_generated_5 } from './string/underscore/is/test/generated/5.mjs';
import { string_underscore_is_test_generated_4 } from './string/underscore/is/test/generated/4.mjs';
import { string_underscore_is_test_generated_3 } from './string/underscore/is/test/generated/3.mjs';
import { string_underscore_is_test_generated_2 } from './string/underscore/is/test/generated/2.mjs';
import { string_underscore_is_test_generated_1 } from './string/underscore/is/test/generated/1.mjs';
import { string_underscore_is_test_7 } from './string/underscore/is/test/7.mjs';
import { string_underscore_is_test_6 } from './string/underscore/is/test/6.mjs';
import { string_underscore_is_test_5 } from './string/underscore/is/test/5.mjs';
import { string_underscore_is_test_4 } from './string/underscore/is/test/4.mjs';
import { string_underscore_is_test_3 } from './string/underscore/is/test/3.mjs';
import { string_underscore_is_test_2 } from './string/underscore/is/test/2.mjs';
import { string_underscore_is_test_1 } from './string/underscore/is/test/1.mjs';
import { string_to_tree_test_generated_5 } from './string/to/tree/test/generated/5.mjs';
import { string_to_tree_test_generated_4 } from './string/to/tree/test/generated/4.mjs';
import { string_to_tree_test_generated_3 } from './string/to/tree/test/generated/3.mjs';
import { string_to_tree_test_generated_2 } from './string/to/tree/test/generated/2.mjs';
import { string_to_tree_test_generated_1 } from './string/to/tree/test/generated/1.mjs';
import { string_to_list_test_generated_5 } from './string/to/list/test/generated/5.mjs';
import { string_to_list_test_generated_4 } from './string/to/list/test/generated/4.mjs';
import { string_to_list_test_generated_3 } from './string/to/list/test/generated/3.mjs';
import { string_to_list_test_generated_2 } from './string/to/list/test/generated/2.mjs';
import { string_to_list_test_generated_1 } from './string/to/list/test/generated/1.mjs';
import { string_swap_test_generated_6 } from './string/swap/test/generated/6.mjs';
import { string_swap_test_generated_2 } from './string/swap/test/generated/2.mjs';
import { string_swap_test_generated_1 } from './string/swap/test/generated/1.mjs';
import { string_suffix_without_test_generated_9 } from './string/suffix/without/test/generated/9.mjs';
import { string_suffix_without_test_generated_8 } from './string/suffix/without/test/generated/8.mjs';
import { string_suffix_without_test_generated_7 } from './string/suffix/without/test/generated/7.mjs';
import { string_suffix_without_test_generated_6 } from './string/suffix/without/test/generated/6.mjs';
import { string_suffix_without_test_generated_5 } from './string/suffix/without/test/generated/5.mjs';
import { string_suffix_without_test_generated_4 } from './string/suffix/without/test/generated/4.mjs';
import { string_suffix_without_test_generated_3 } from './string/suffix/without/test/generated/3.mjs';
import { string_suffix_without_test_generated_2 } from './string/suffix/without/test/generated/2.mjs';
import { string_suffix_without_test_generated_10 } from './string/suffix/without/test/generated/10.mjs';
import { string_suffix_without_test_generated_1 } from './string/suffix/without/test/generated/1.mjs';
import { string_sub_test_generated_9 } from './string/sub/test/generated/9.mjs';
import { string_sub_test_generated_8 } from './string/sub/test/generated/8.mjs';
import { string_sub_test_generated_7 } from './string/sub/test/generated/7.mjs';
import { string_sub_test_generated_6 } from './string/sub/test/generated/6.mjs';
import { string_sub_test_generated_5 } from './string/sub/test/generated/5.mjs';
import { string_sub_test_generated_4 } from './string/sub/test/generated/4.mjs';
import { string_sub_test_generated_3 } from './string/sub/test/generated/3.mjs';
import { string_sub_test_generated_2 } from './string/sub/test/generated/2.mjs';
import { string_sub_test_generated_10 } from './string/sub/test/generated/10.mjs';
import { string_sub_test_generated_1 } from './string/sub/test/generated/1.mjs';
import { string_sub_max_test_generated_9 } from './string/sub/max/test/generated/9.mjs';
import { string_sub_max_test_generated_8 } from './string/sub/max/test/generated/8.mjs';
import { string_sub_max_test_generated_7 } from './string/sub/max/test/generated/7.mjs';
import { string_sub_max_test_generated_6 } from './string/sub/max/test/generated/6.mjs';
import { string_sub_max_test_generated_5 } from './string/sub/max/test/generated/5.mjs';
import { string_sub_max_test_generated_4 } from './string/sub/max/test/generated/4.mjs';
import { string_sub_max_test_generated_3 } from './string/sub/max/test/generated/3.mjs';
import { string_sub_max_test_generated_2 } from './string/sub/max/test/generated/2.mjs';
import { string_sub_max_test_generated_10 } from './string/sub/max/test/generated/10.mjs';
import { string_sub_max_test_generated_1 } from './string/sub/max/test/generated/1.mjs';
import { string_sub_max_3_test_generated_7 } from './string/sub/max/3/test/generated/7.mjs';
import { string_sub_max_3_test_generated_6 } from './string/sub/max/3/test/generated/6.mjs';
import { string_sub_max_3_test_generated_5 } from './string/sub/max/3/test/generated/5.mjs';
import { string_sub_max_3_test_generated_4 } from './string/sub/max/3/test/generated/4.mjs';
import { string_sub_max_3_test_generated_3 } from './string/sub/max/3/test/generated/3.mjs';
import { string_sub_max_3_test_generated_2 } from './string/sub/max/3/test/generated/2.mjs';
import { string_sub_max_3_test_generated_10 } from './string/sub/max/3/test/generated/10.mjs';
import { string_sub_max_3_test_generated_1 } from './string/sub/max/3/test/generated/1.mjs';
import { string_sub_max_2_test_generated_9 } from './string/sub/max/2/test/generated/9.mjs';
import { string_sub_max_2_test_generated_8 } from './string/sub/max/2/test/generated/8.mjs';
import { string_sub_max_2_test_generated_7 } from './string/sub/max/2/test/generated/7.mjs';
import { string_sub_max_2_test_generated_6 } from './string/sub/max/2/test/generated/6.mjs';
import { string_sub_max_2_test_generated_5 } from './string/sub/max/2/test/generated/5.mjs';
import { string_sub_max_2_test_generated_4 } from './string/sub/max/2/test/generated/4.mjs';
import { string_sub_max_2_test_generated_3 } from './string/sub/max/2/test/generated/3.mjs';
import { string_sub_max_2_test_generated_2 } from './string/sub/max/2/test/generated/2.mjs';
import { string_sub_max_2_test_generated_10 } from './string/sub/max/2/test/generated/10.mjs';
import { string_sub_max_2_test_generated_1 } from './string/sub/max/2/test/generated/1.mjs';
import { string_starts_with_test_generated_9 } from './string/starts/with/test/generated/9.mjs';
import { string_starts_with_test_generated_8 } from './string/starts/with/test/generated/8.mjs';
import { string_starts_with_test_generated_7 } from './string/starts/with/test/generated/7.mjs';
import { string_starts_with_test_generated_6 } from './string/starts/with/test/generated/6.mjs';
import { string_starts_with_test_generated_5 } from './string/starts/with/test/generated/5.mjs';
import { string_starts_with_test_generated_4 } from './string/starts/with/test/generated/4.mjs';
import { string_starts_with_test_generated_3 } from './string/starts/with/test/generated/3.mjs';
import { string_starts_with_test_generated_2 } from './string/starts/with/test/generated/2.mjs';
import { string_starts_with_test_generated_10 } from './string/starts/with/test/generated/10.mjs';
import { string_starts_with_test_generated_1 } from './string/starts/with/test/generated/1.mjs';
import { string_split_test_generated_9 } from './string/split/test/generated/9.mjs';
import { string_split_test_generated_8 } from './string/split/test/generated/8.mjs';
import { string_split_test_generated_7 } from './string/split/test/generated/7.mjs';
import { string_split_test_generated_6 } from './string/split/test/generated/6.mjs';
import { string_split_test_generated_5 } from './string/split/test/generated/5.mjs';
import { string_split_test_generated_4 } from './string/split/test/generated/4.mjs';
import { string_split_test_generated_3 } from './string/split/test/generated/3.mjs';
import { string_split_test_generated_2 } from './string/split/test/generated/2.mjs';
import { string_split_test_generated_10 } from './string/split/test/generated/10.mjs';
import { string_split_test_generated_1 } from './string/split/test/generated/1.mjs';
import { string_skip_test_generated_9 } from './string/skip/test/generated/9.mjs';
import { string_skip_test_generated_8 } from './string/skip/test/generated/8.mjs';
import { string_skip_test_generated_7 } from './string/skip/test/generated/7.mjs';
import { string_skip_test_generated_6 } from './string/skip/test/generated/6.mjs';
import { string_skip_test_generated_5 } from './string/skip/test/generated/5.mjs';
import { string_skip_test_generated_4 } from './string/skip/test/generated/4.mjs';
import { string_skip_test_generated_3 } from './string/skip/test/generated/3.mjs';
import { string_skip_test_generated_2 } from './string/skip/test/generated/2.mjs';
import { string_skip_test_generated_10 } from './string/skip/test/generated/10.mjs';
import { string_skip_test_generated_1 } from './string/skip/test/generated/1.mjs';
import { string_similar_test_generated_9 } from './string/similar/test/generated/9.mjs';
import { string_similar_test_generated_8 } from './string/similar/test/generated/8.mjs';
import { string_similar_test_generated_7 } from './string/similar/test/generated/7.mjs';
import { string_similar_test_generated_6 } from './string/similar/test/generated/6.mjs';
import { string_similar_test_generated_5 } from './string/similar/test/generated/5.mjs';
import { string_similar_test_generated_4 } from './string/similar/test/generated/4.mjs';
import { string_similar_test_generated_3 } from './string/similar/test/generated/3.mjs';
import { string_similar_test_generated_20 } from './string/similar/test/generated/20.mjs';
import { string_similar_test_generated_2 } from './string/similar/test/generated/2.mjs';
import { string_similar_test_generated_19 } from './string/similar/test/generated/19.mjs';
import { string_similar_test_generated_18 } from './string/similar/test/generated/18.mjs';
import { string_similar_test_generated_17 } from './string/similar/test/generated/17.mjs';
import { string_similar_test_generated_16 } from './string/similar/test/generated/16.mjs';
import { string_similar_test_generated_15 } from './string/similar/test/generated/15.mjs';
import { string_similar_test_generated_14 } from './string/similar/test/generated/14.mjs';
import { string_similar_test_generated_13 } from './string/similar/test/generated/13.mjs';
import { string_similar_test_generated_12 } from './string/similar/test/generated/12.mjs';
import { string_similar_test_generated_11 } from './string/similar/test/generated/11.mjs';
import { string_similar_test_generated_10 } from './string/similar/test/generated/10.mjs';
import { string_similar_test_generated_1 } from './string/similar/test/generated/1.mjs';
import { string_set_test_generated_4 } from './string/set/test/generated/4.mjs';
import { string_set_test_generated_3 } from './string/set/test/generated/3.mjs';
import { string_set_test_generated_2 } from './string/set/test/generated/2.mjs';
import { string_set_test_generated_10 } from './string/set/test/generated/10.mjs';
import { string_set_test_generated_1 } from './string/set/test/generated/1.mjs';
import { string_replace_test_generated_9 } from './string/replace/test/generated/9.mjs';
import { string_replace_test_generated_8 } from './string/replace/test/generated/8.mjs';
import { string_replace_test_generated_7 } from './string/replace/test/generated/7.mjs';
import { string_replace_test_generated_6 } from './string/replace/test/generated/6.mjs';
import { string_replace_test_generated_5 } from './string/replace/test/generated/5.mjs';
import { string_replace_test_generated_4 } from './string/replace/test/generated/4.mjs';
import { string_replace_test_generated_3 } from './string/replace/test/generated/3.mjs';
import { string_replace_test_generated_2 } from './string/replace/test/generated/2.mjs';
import { string_replace_test_generated_10 } from './string/replace/test/generated/10.mjs';
import { string_replace_test_generated_1 } from './string/replace/test/generated/1.mjs';
import { string_repeat_is_test_generated_5 } from './string/repeat/is/test/generated/5.mjs';
import { string_repeat_is_test_generated_4 } from './string/repeat/is/test/generated/4.mjs';
import { string_repeat_is_test_generated_3 } from './string/repeat/is/test/generated/3.mjs';
import { string_repeat_is_test_generated_2 } from './string/repeat/is/test/generated/2.mjs';
import { string_repeat_is_test_generated_1 } from './string/repeat/is/test/generated/1.mjs';
import { string_remove_at_test_generated_9 } from './string/remove/at/test/generated/9.mjs';
import { string_remove_at_test_generated_8 } from './string/remove/at/test/generated/8.mjs';
import { string_remove_at_test_generated_4 } from './string/remove/at/test/generated/4.mjs';
import { string_remove_at_test_generated_3 } from './string/remove/at/test/generated/3.mjs';
import { string_remove_at_test_generated_2 } from './string/remove/at/test/generated/2.mjs';
import { string_remove_at_test_generated_1 } from './string/remove/at/test/generated/1.mjs';
import { string_prefix_without_test_generated_9 } from './string/prefix/without/test/generated/9.mjs';
import { string_prefix_without_test_generated_8 } from './string/prefix/without/test/generated/8.mjs';
import { string_prefix_without_test_generated_7 } from './string/prefix/without/test/generated/7.mjs';
import { string_prefix_without_test_generated_6 } from './string/prefix/without/test/generated/6.mjs';
import { string_prefix_without_test_generated_5 } from './string/prefix/without/test/generated/5.mjs';
import { string_prefix_without_test_generated_4 } from './string/prefix/without/test/generated/4.mjs';
import { string_prefix_without_test_generated_3 } from './string/prefix/without/test/generated/3.mjs';
import { string_prefix_without_test_generated_2 } from './string/prefix/without/test/generated/2.mjs';
import { string_prefix_without_test_generated_10 } from './string/prefix/without/test/generated/10.mjs';
import { string_prefix_without_test_generated_1 } from './string/prefix/without/test/generated/1.mjs';
import { string_prefix_replace_test_generated_9 } from './string/prefix/replace/test/generated/9.mjs';
import { string_prefix_replace_test_generated_8 } from './string/prefix/replace/test/generated/8.mjs';
import { string_prefix_replace_test_generated_7 } from './string/prefix/replace/test/generated/7.mjs';
import { string_prefix_replace_test_generated_6 } from './string/prefix/replace/test/generated/6.mjs';
import { string_prefix_replace_test_generated_5 } from './string/prefix/replace/test/generated/5.mjs';
import { string_prefix_replace_test_generated_4 } from './string/prefix/replace/test/generated/4.mjs';
import { string_prefix_replace_test_generated_3 } from './string/prefix/replace/test/generated/3.mjs';
import { string_prefix_replace_test_generated_2 } from './string/prefix/replace/test/generated/2.mjs';
import { string_prefix_replace_test_generated_10 } from './string/prefix/replace/test/generated/10.mjs';
import { string_prefix_replace_test_generated_1 } from './string/prefix/replace/test/generated/1.mjs';
import { string_new_line_test_generated_1 } from './string/new/line/test/generated/1.mjs';
import { string_letter_is_test_generated_5 } from './string/letter/is/test/generated/5.mjs';
import { string_letter_is_test_generated_4 } from './string/letter/is/test/generated/4.mjs';
import { string_letter_is_test_generated_3 } from './string/letter/is/test/generated/3.mjs';
import { string_letter_is_test_generated_2 } from './string/letter/is/test/generated/2.mjs';
import { string_letter_is_test_generated_1 } from './string/letter/is/test/generated/1.mjs';
import { string_letter_is_test_7 } from './string/letter/is/test/7.mjs';
import { string_letter_is_test_6 } from './string/letter/is/test/6.mjs';
import { string_letter_is_test_5 } from './string/letter/is/test/5.mjs';
import { string_letter_is_test_4 } from './string/letter/is/test/4.mjs';
import { string_letter_is_test_3 } from './string/letter/is/test/3.mjs';
import { string_letter_is_test_2 } from './string/letter/is/test/2.mjs';
import { string_letter_is_test_1 } from './string/letter/is/test/1.mjs';
import { string_letter_digit_or_underscore_is_test_generated_5 } from './string/letter/digit/or/underscore/is/test/generated/5.mjs';
import { string_letter_digit_or_underscore_is_test_generated_4 } from './string/letter/digit/or/underscore/is/test/generated/4.mjs';
import { string_letter_digit_or_underscore_is_test_generated_3 } from './string/letter/digit/or/underscore/is/test/generated/3.mjs';
import { string_letter_digit_or_underscore_is_test_generated_2 } from './string/letter/digit/or/underscore/is/test/generated/2.mjs';
import { string_letter_digit_or_underscore_is_test_generated_1 } from './string/letter/digit/or/underscore/is/test/generated/1.mjs';
import { string_letter_digit_or_underscore_is_test_7 } from './string/letter/digit/or/underscore/is/test/7.mjs';
import { string_letter_digit_or_underscore_is_test_6 } from './string/letter/digit/or/underscore/is/test/6.mjs';
import { string_letter_digit_or_underscore_is_test_5 } from './string/letter/digit/or/underscore/is/test/5.mjs';
import { string_letter_digit_or_underscore_is_test_4 } from './string/letter/digit/or/underscore/is/test/4.mjs';
import { string_letter_digit_or_underscore_is_test_3 } from './string/letter/digit/or/underscore/is/test/3.mjs';
import { string_letter_digit_or_underscore_is_test_2 } from './string/letter/digit/or/underscore/is/test/2.mjs';
import { string_letter_digit_or_underscore_is_test_1 } from './string/letter/digit/or/underscore/is/test/1.mjs';
import { string_index_of_try_test_generated_9 } from './string/index/of/try/test/generated/9.mjs';
import { string_index_of_try_test_generated_8 } from './string/index/of/try/test/generated/8.mjs';
import { string_index_of_try_test_generated_7 } from './string/index/of/try/test/generated/7.mjs';
import { string_index_of_try_test_generated_6 } from './string/index/of/try/test/generated/6.mjs';
import { string_index_of_try_test_generated_5 } from './string/index/of/try/test/generated/5.mjs';
import { string_index_of_try_test_generated_4 } from './string/index/of/try/test/generated/4.mjs';
import { string_index_of_try_test_generated_3 } from './string/index/of/try/test/generated/3.mjs';
import { string_index_of_try_test_generated_2 } from './string/index/of/try/test/generated/2.mjs';
import { string_index_of_try_test_generated_10 } from './string/index/of/try/test/generated/10.mjs';
import { string_index_of_try_test_generated_1 } from './string/index/of/try/test/generated/1.mjs';
import { string_index_of_test_generated_8 } from './string/index/of/test/generated/8.mjs';
import { string_index_of_test_generated_6 } from './string/index/of/test/generated/6.mjs';
import { string_index_of_test_generated_5 } from './string/index/of/test/generated/5.mjs';
import { string_index_of_test_generated_4 } from './string/index/of/test/generated/4.mjs';
import { string_index_of_test_generated_2 } from './string/index/of/test/generated/2.mjs';
import { string_index_of_test_generated_10 } from './string/index/of/test/generated/10.mjs';
import { string_index_of_test_generated_1 } from './string/index/of/test/generated/1.mjs';
import { string_includes_test_generated_9 } from './string/includes/test/generated/9.mjs';
import { string_includes_test_generated_8 } from './string/includes/test/generated/8.mjs';
import { string_includes_test_generated_7 } from './string/includes/test/generated/7.mjs';
import { string_includes_test_generated_6 } from './string/includes/test/generated/6.mjs';
import { string_includes_test_generated_5 } from './string/includes/test/generated/5.mjs';
import { string_includes_test_generated_4 } from './string/includes/test/generated/4.mjs';
import { string_includes_test_generated_3 } from './string/includes/test/generated/3.mjs';
import { string_includes_test_generated_2 } from './string/includes/test/generated/2.mjs';
import { string_includes_test_generated_10 } from './string/includes/test/generated/10.mjs';
import { string_includes_test_generated_1 } from './string/includes/test/generated/1.mjs';
import { string_function_tests_sub_test_generated_1 } from './string/function/tests/sub/test/generated/1.mjs';
import { string_function_tests_name_is_test_generated_5 } from './string/function/tests/name/is/test/generated/5.mjs';
import { string_function_tests_name_is_test_generated_4 } from './string/function/tests/name/is/test/generated/4.mjs';
import { string_function_tests_name_is_test_generated_3 } from './string/function/tests/name/is/test/generated/3.mjs';
import { string_function_tests_name_is_test_generated_2 } from './string/function/tests/name/is/test/generated/2.mjs';
import { string_function_tests_name_is_test_generated_1 } from './string/function/tests/name/is/test/generated/1.mjs';
import { string_function_tests_name_is_test_6 } from './string/function/tests/name/is/test/6.mjs';
import { string_function_tests_name_is_test_5 } from './string/function/tests/name/is/test/5.mjs';
import { string_function_tests_name_is_test_4 } from './string/function/tests/name/is/test/4.mjs';
import { string_function_tests_name_is_test_3 } from './string/function/tests/name/is/test/3.mjs';
import { string_function_tests_name_is_test_2 } from './string/function/tests/name/is/test/2.mjs';
import { string_function_tests_name_is_test_1 } from './string/function/tests/name/is/test/1.mjs';
import { string_equal_except_1_test_generated_9 } from './string/equal/except/1/test/generated/9.mjs';
import { string_equal_except_1_test_generated_8 } from './string/equal/except/1/test/generated/8.mjs';
import { string_equal_except_1_test_generated_7 } from './string/equal/except/1/test/generated/7.mjs';
import { string_equal_except_1_test_generated_6 } from './string/equal/except/1/test/generated/6.mjs';
import { string_equal_except_1_test_generated_5 } from './string/equal/except/1/test/generated/5.mjs';
import { string_equal_except_1_test_generated_4 } from './string/equal/except/1/test/generated/4.mjs';
import { string_equal_except_1_test_generated_3 } from './string/equal/except/1/test/generated/3.mjs';
import { string_equal_except_1_test_generated_2 } from './string/equal/except/1/test/generated/2.mjs';
import { string_equal_except_1_test_generated_10 } from './string/equal/except/1/test/generated/10.mjs';
import { string_equal_except_1_test_generated_1 } from './string/equal/except/1/test/generated/1.mjs';
import { string_equal_count_test_generated_9 } from './string/equal/count/test/generated/9.mjs';
import { string_equal_count_test_generated_8 } from './string/equal/count/test/generated/8.mjs';
import { string_equal_count_test_generated_7 } from './string/equal/count/test/generated/7.mjs';
import { string_equal_count_test_generated_6 } from './string/equal/count/test/generated/6.mjs';
import { string_equal_count_test_generated_5 } from './string/equal/count/test/generated/5.mjs';
import { string_equal_count_test_generated_4 } from './string/equal/count/test/generated/4.mjs';
import { string_equal_count_test_generated_3 } from './string/equal/count/test/generated/3.mjs';
import { string_equal_count_test_generated_2 } from './string/equal/count/test/generated/2.mjs';
import { string_equal_count_test_generated_10 } from './string/equal/count/test/generated/10.mjs';
import { string_equal_count_test_generated_1 } from './string/equal/count/test/generated/1.mjs';
import { string_ends_with_test_generated_9 } from './string/ends/with/test/generated/9.mjs';
import { string_ends_with_test_generated_8 } from './string/ends/with/test/generated/8.mjs';
import { string_ends_with_test_generated_7 } from './string/ends/with/test/generated/7.mjs';
import { string_ends_with_test_generated_6 } from './string/ends/with/test/generated/6.mjs';
import { string_ends_with_test_generated_5 } from './string/ends/with/test/generated/5.mjs';
import { string_ends_with_test_generated_4 } from './string/ends/with/test/generated/4.mjs';
import { string_ends_with_test_generated_3 } from './string/ends/with/test/generated/3.mjs';
import { string_ends_with_test_generated_2 } from './string/ends/with/test/generated/2.mjs';
import { string_ends_with_test_generated_10 } from './string/ends/with/test/generated/10.mjs';
import { string_ends_with_test_generated_1 } from './string/ends/with/test/generated/1.mjs';
import { string_empty_not_is_test_generated_5 } from './string/empty/not/is/test/generated/5.mjs';
import { string_empty_not_is_test_generated_4 } from './string/empty/not/is/test/generated/4.mjs';
import { string_empty_not_is_test_generated_3 } from './string/empty/not/is/test/generated/3.mjs';
import { string_empty_not_is_test_generated_2 } from './string/empty/not/is/test/generated/2.mjs';
import { string_empty_not_is_test_generated_1 } from './string/empty/not/is/test/generated/1.mjs';
import { string_empty_is_test_generated_5 } from './string/empty/is/test/generated/5.mjs';
import { string_empty_is_test_generated_4 } from './string/empty/is/test/generated/4.mjs';
import { string_empty_is_test_generated_3 } from './string/empty/is/test/generated/3.mjs';
import { string_empty_is_test_generated_2 } from './string/empty/is/test/generated/2.mjs';
import { string_empty_is_test_generated_1 } from './string/empty/is/test/generated/1.mjs';
import { string_digit_is_test_generated_5 } from './string/digit/is/test/generated/5.mjs';
import { string_digit_is_test_generated_4 } from './string/digit/is/test/generated/4.mjs';
import { string_digit_is_test_generated_3 } from './string/digit/is/test/generated/3.mjs';
import { string_digit_is_test_generated_2 } from './string/digit/is/test/generated/2.mjs';
import { string_digit_is_test_generated_1 } from './string/digit/is/test/generated/1.mjs';
import { string_digit_is_test_9 } from './string/digit/is/test/9.mjs';
import { string_digit_is_test_8 } from './string/digit/is/test/8.mjs';
import { string_digit_is_test_7 } from './string/digit/is/test/7.mjs';
import { string_digit_is_test_6 } from './string/digit/is/test/6.mjs';
import { string_digit_is_test_5 } from './string/digit/is/test/5.mjs';
import { string_digit_is_test_4 } from './string/digit/is/test/4.mjs';
import { string_digit_is_test_3 } from './string/digit/is/test/3.mjs';
import { string_digit_is_test_2 } from './string/digit/is/test/2.mjs';
import { string_digit_is_test_12 } from './string/digit/is/test/12.mjs';
import { string_digit_is_test_11 } from './string/digit/is/test/11.mjs';
import { string_digit_is_test_10 } from './string/digit/is/test/10.mjs';
import { string_digit_is_test_1 } from './string/digit/is/test/1.mjs';
import { string_difference_tests_test_generated_9 } from './string/difference/tests/test/generated/9.mjs';
import { string_difference_tests_test_generated_8 } from './string/difference/tests/test/generated/8.mjs';
import { string_difference_tests_test_generated_7 } from './string/difference/tests/test/generated/7.mjs';
import { string_difference_tests_test_generated_6 } from './string/difference/tests/test/generated/6.mjs';
import { string_difference_tests_test_generated_5 } from './string/difference/tests/test/generated/5.mjs';
import { string_difference_tests_test_generated_4 } from './string/difference/tests/test/generated/4.mjs';
import { string_difference_tests_test_generated_3 } from './string/difference/tests/test/generated/3.mjs';
import { string_difference_tests_test_generated_2 } from './string/difference/tests/test/generated/2.mjs';
import { string_difference_tests_test_generated_10 } from './string/difference/tests/test/generated/10.mjs';
import { string_difference_tests_test_generated_1 } from './string/difference/tests/test/generated/1.mjs';
import { string_difference_get_test_9 } from './string/difference/get/test/9.mjs';
import { string_difference_get_test_8 } from './string/difference/get/test/8.mjs';
import { string_difference_get_test_7 } from './string/difference/get/test/7.mjs';
import { string_difference_get_test_6 } from './string/difference/get/test/6.mjs';
import { string_difference_get_test_5 } from './string/difference/get/test/5.mjs';
import { string_difference_get_test_4 } from './string/difference/get/test/4.mjs';
import { string_difference_get_test_3 } from './string/difference/get/test/3.mjs';
import { string_difference_get_test_23 } from './string/difference/get/test/23.mjs';
import { string_difference_get_test_22 } from './string/difference/get/test/22.mjs';
import { string_difference_get_test_21 } from './string/difference/get/test/21.mjs';
import { string_difference_get_test_20 } from './string/difference/get/test/20.mjs';
import { string_difference_get_test_2 } from './string/difference/get/test/2.mjs';
import { string_difference_get_test_19 } from './string/difference/get/test/19.mjs';
import { string_difference_get_test_18 } from './string/difference/get/test/18.mjs';
import { string_difference_get_test_17 } from './string/difference/get/test/17.mjs';
import { string_difference_get_test_16 } from './string/difference/get/test/16.mjs';
import { string_difference_get_test_15 } from './string/difference/get/test/15.mjs';
import { string_difference_get_test_14 } from './string/difference/get/test/14.mjs';
import { string_difference_get_test_13 } from './string/difference/get/test/13.mjs';
import { string_difference_get_test_12 } from './string/difference/get/test/12.mjs';
import { string_difference_get_test_11 } from './string/difference/get/test/11.mjs';
import { string_difference_get_test_10 } from './string/difference/get/test/10.mjs';
import { string_difference_get_test_1 } from './string/difference/get/test/1.mjs';
import { string_difference_get_external_test_generated_9 } from './string/difference/get/external/test/generated/9.mjs';
import { string_difference_get_external_test_generated_8 } from './string/difference/get/external/test/generated/8.mjs';
import { string_difference_get_external_test_generated_7 } from './string/difference/get/external/test/generated/7.mjs';
import { string_difference_get_external_test_generated_6 } from './string/difference/get/external/test/generated/6.mjs';
import { string_difference_get_external_test_generated_5 } from './string/difference/get/external/test/generated/5.mjs';
import { string_difference_get_external_test_generated_4 } from './string/difference/get/external/test/generated/4.mjs';
import { string_difference_get_external_test_generated_3 } from './string/difference/get/external/test/generated/3.mjs';
import { string_difference_get_external_test_generated_2 } from './string/difference/get/external/test/generated/2.mjs';
import { string_difference_get_external_test_generated_10 } from './string/difference/get/external/test/generated/10.mjs';
import { string_difference_get_external_test_generated_1 } from './string/difference/get/external/test/generated/1.mjs';
import { string_difference_apply_test_9 } from './string/difference/apply/test/9.mjs';
import { string_difference_apply_test_8 } from './string/difference/apply/test/8.mjs';
import { string_difference_apply_test_7 } from './string/difference/apply/test/7.mjs';
import { string_difference_apply_test_6 } from './string/difference/apply/test/6.mjs';
import { string_difference_apply_test_5 } from './string/difference/apply/test/5.mjs';
import { string_difference_apply_test_4 } from './string/difference/apply/test/4.mjs';
import { string_difference_apply_test_3 } from './string/difference/apply/test/3.mjs';
import { string_difference_apply_test_2 } from './string/difference/apply/test/2.mjs';
import { string_difference_apply_test_10 } from './string/difference/apply/test/10.mjs';
import { string_difference_apply_test_1 } from './string/difference/apply/test/1.mjs';
import { string_difference_apply_parse_test_4 } from './string/difference/apply/parse/test/4.mjs';
import { string_difference_apply_parse_test_3 } from './string/difference/apply/parse/test/3.mjs';
import { string_difference_apply_parse_test_2 } from './string/difference/apply/parse/test/2.mjs';
import { string_difference_apply_parse_test_1 } from './string/difference/apply/parse/test/1.mjs';
import { string_case_upper_character_first_test_generated_5 } from './string/case/upper/character/first/test/generated/5.mjs';
import { string_case_upper_character_first_test_generated_4 } from './string/case/upper/character/first/test/generated/4.mjs';
import { string_case_upper_character_first_test_generated_3 } from './string/case/upper/character/first/test/generated/3.mjs';
import { string_case_upper_character_first_test_generated_2 } from './string/case/upper/character/first/test/generated/2.mjs';
import { string_case_upper_character_first_test_generated_1 } from './string/case/upper/character/first/test/generated/1.mjs';
import { string_case_snake_to_pascal_test_generated_5 } from './string/case/snake/to/pascal/test/generated/5.mjs';
import { string_case_snake_to_pascal_test_generated_4 } from './string/case/snake/to/pascal/test/generated/4.mjs';
import { string_case_snake_to_pascal_test_generated_3 } from './string/case/snake/to/pascal/test/generated/3.mjs';
import { string_case_snake_to_pascal_test_generated_2 } from './string/case/snake/to/pascal/test/generated/2.mjs';
import { string_case_snake_to_pascal_test_generated_1 } from './string/case/snake/to/pascal/test/generated/1.mjs';
import { string_a_test_generated_1 } from './string/a/test/generated/1.mjs';
import { range_from_test_generated_8 } from './range/from/test/generated/8.mjs';
import { range_from_test_generated_7 } from './range/from/test/generated/7.mjs';
import { range_from_test_generated_6 } from './range/from/test/generated/6.mjs';
import { range_from_test_generated_5 } from './range/from/test/generated/5.mjs';
import { range_from_test_generated_4 } from './range/from/test/generated/4.mjs';
import { range_from_test_generated_3 } from './range/from/test/generated/3.mjs';
import { range_from_test_generated_2 } from './range/from/test/generated/2.mjs';
import { range_from_test_generated_10 } from './range/from/test/generated/10.mjs';
import { range_from_test_generated_1 } from './range/from/test/generated/1.mjs';
import { js_identifier_sub_is_test_generated_5 } from './js/identifier/sub/is/test/generated/5.mjs';
import { js_identifier_sub_is_test_generated_4 } from './js/identifier/sub/is/test/generated/4.mjs';
import { js_identifier_sub_is_test_generated_3 } from './js/identifier/sub/is/test/generated/3.mjs';
import { js_identifier_sub_is_test_generated_2 } from './js/identifier/sub/is/test/generated/2.mjs';
import { js_identifier_sub_is_test_generated_1 } from './js/identifier/sub/is/test/generated/1.mjs';
import { js_identifier_sub_is_test_9 } from './js/identifier/sub/is/test/9.mjs';
import { js_identifier_sub_is_test_8 } from './js/identifier/sub/is/test/8.mjs';
import { js_identifier_sub_is_test_7 } from './js/identifier/sub/is/test/7.mjs';
import { js_identifier_sub_is_test_6 } from './js/identifier/sub/is/test/6.mjs';
import { js_identifier_sub_is_test_5 } from './js/identifier/sub/is/test/5.mjs';
import { js_identifier_sub_is_test_4 } from './js/identifier/sub/is/test/4.mjs';
import { js_identifier_sub_is_test_3 } from './js/identifier/sub/is/test/3.mjs';
import { js_identifier_sub_is_test_2 } from './js/identifier/sub/is/test/2.mjs';
import { js_identifier_sub_is_test_10 } from './js/identifier/sub/is/test/10.mjs';
import { js_identifier_sub_is_test_1 } from './js/identifier/sub/is/test/1.mjs';
import { js_identifier_is_test_generated_5 } from './js/identifier/is/test/generated/5.mjs';
import { js_identifier_is_test_generated_4 } from './js/identifier/is/test/generated/4.mjs';
import { js_identifier_is_test_generated_3 } from './js/identifier/is/test/generated/3.mjs';
import { js_identifier_is_test_generated_2 } from './js/identifier/is/test/generated/2.mjs';
import { js_identifier_is_test_generated_1 } from './js/identifier/is/test/generated/1.mjs';
import { js_identifier_is_test_9 } from './js/identifier/is/test/9.mjs';
import { js_identifier_is_test_8 } from './js/identifier/is/test/8.mjs';
import { js_identifier_is_test_7 } from './js/identifier/is/test/7.mjs';
import { js_identifier_is_test_6 } from './js/identifier/is/test/6.mjs';
import { js_identifier_is_test_5 } from './js/identifier/is/test/5.mjs';
import { js_identifier_is_test_4 } from './js/identifier/is/test/4.mjs';
import { js_identifier_is_test_3 } from './js/identifier/is/test/3.mjs';
import { js_identifier_is_test_2 } from './js/identifier/is/test/2.mjs';
import { js_identifier_is_test_10 } from './js/identifier/is/test/10.mjs';
import { js_identifier_is_test_1 } from './js/identifier/is/test/1.mjs';
import { integer_mod_test_generated_9 } from './integer/mod/test/generated/9.mjs';
import { integer_mod_test_generated_8 } from './integer/mod/test/generated/8.mjs';
import { integer_mod_test_generated_7 } from './integer/mod/test/generated/7.mjs';
import { integer_mod_test_generated_6 } from './integer/mod/test/generated/6.mjs';
import { integer_mod_test_generated_5 } from './integer/mod/test/generated/5.mjs';
import { integer_mod_test_generated_4 } from './integer/mod/test/generated/4.mjs';
import { integer_mod_test_generated_3 } from './integer/mod/test/generated/3.mjs';
import { integer_mod_test_generated_2 } from './integer/mod/test/generated/2.mjs';
import { integer_mod_test_generated_10 } from './integer/mod/test/generated/10.mjs';
import { integer_mod_test_generated_1 } from './integer/mod/test/generated/1.mjs';
import { integer_half_test_generated_5 } from './integer/half/test/generated/5.mjs';
import { integer_half_test_generated_4 } from './integer/half/test/generated/4.mjs';
import { integer_half_test_generated_3 } from './integer/half/test/generated/3.mjs';
import { integer_half_test_generated_2 } from './integer/half/test/generated/2.mjs';
import { integer_half_test_generated_1 } from './integer/half/test/generated/1.mjs';
import { integer_even_is_test_generated_6 } from './integer/even/is/test/generated/6.mjs';
import { integer_even_is_test_generated_5 } from './integer/even/is/test/generated/5.mjs';
import { integer_even_is_test_generated_4 } from './integer/even/is/test/generated/4.mjs';
import { integer_even_is_test_generated_3 } from './integer/even/is/test/generated/3.mjs';
import { integer_even_is_test_generated_2 } from './integer/even/is/test/generated/2.mjs';
import { integer_even_is_test_generated_1 } from './integer/even/is/test/generated/1.mjs';
import { integer_divide_evenly_test_generated_9 } from './integer/divide/evenly/test/generated/9.mjs';
import { integer_divide_evenly_test_generated_8 } from './integer/divide/evenly/test/generated/8.mjs';
import { integer_divide_evenly_test_generated_5 } from './integer/divide/evenly/test/generated/5.mjs';
import { integer_divide_evenly_test_generated_4 } from './integer/divide/evenly/test/generated/4.mjs';
import { integer_divide_evenly_test_generated_3 } from './integer/divide/evenly/test/generated/3.mjs';
import { integer_divide_evenly_test_generated_2 } from './integer/divide/evenly/test/generated/2.mjs';
import { integer_divide_evenly_test_generated_1 } from './integer/divide/evenly/test/generated/1.mjs';
import { error_test_3 } from './error/test/3.mjs';
import { error_test_2 } from './error/test/2.mjs';
import { error_test_1 } from './error/test/1.mjs';
import { comment_test_3 } from './comment/test/3.mjs';
import { comment_test_2 } from './comment/test/2.mjs';
import { comment_test_1 } from './comment/test/1.mjs';
import { assert_test_5 } from './assert/test/5.mjs';
import { assert_test_4 } from './assert/test/4.mjs';
import { assert_test_3 } from './assert/test/3.mjs';
import { assert_test_2 } from './assert/test/2.mjs';
import { assert_test_1 } from './assert/test/1.mjs';
import { arguments_count_test_5 } from './arguments/count/test/5.mjs';
import { arguments_count_test_4 } from './arguments/count/test/4.mjs';
import { arguments_count_test_3 } from './arguments/count/test/3.mjs';
import { arguments_count_test_2 } from './arguments/count/test/2.mjs';
import { arguments_count_test_1 } from './arguments/count/test/1.mjs';
import { arguments_assert_test_4 } from './arguments/assert/test/4.mjs';
import { arguments_assert_test_3 } from './arguments/assert/test/3.mjs';
import { arguments_assert_test_2 } from './arguments/assert/test/2.mjs';
import { arguments_assert_test_1 } from './arguments/assert/test/1.mjs';
import { add_1_test_6 } from './add/1/test/6.mjs';
import { add_1_test_5 } from './add/1/test/5.mjs';
import { add_1_test_4 } from './add/1/test/4.mjs';
import { add_1_test_3 } from './add/1/test/3.mjs';
import { add_1_test_2 } from './add/1/test/2.mjs';
import { add_1_test_1 } from './add/1/test/1.mjs';
import { arguments_assert } from './arguments/assert.mjs';
export async function tests() {
    arguments_assert(arguments, []);
    await add_1_test_1();
    await add_1_test_2();
    await add_1_test_3();
    await add_1_test_4();
    await add_1_test_5();
    await add_1_test_6();
    await arguments_assert_test_1();
    await arguments_assert_test_2();
    await arguments_assert_test_3();
    await arguments_assert_test_4();
    await arguments_count_test_1();
    await arguments_count_test_2();
    await arguments_count_test_3();
    await arguments_count_test_4();
    await arguments_count_test_5();
    await assert_test_1();
    await assert_test_2();
    await assert_test_3();
    await assert_test_4();
    await assert_test_5();
    await comment_test_1();
    await comment_test_2();
    await comment_test_3();
    await error_test_1();
    await error_test_2();
    await error_test_3();
    await integer_divide_evenly_test_generated_1();
    await integer_divide_evenly_test_generated_2();
    await integer_divide_evenly_test_generated_3();
    await integer_divide_evenly_test_generated_4();
    await integer_divide_evenly_test_generated_5();
    await integer_divide_evenly_test_generated_8();
    await integer_divide_evenly_test_generated_9();
    await integer_even_is_test_generated_1();
    await integer_even_is_test_generated_2();
    await integer_even_is_test_generated_3();
    await integer_even_is_test_generated_4();
    await integer_even_is_test_generated_5();
    await integer_even_is_test_generated_6();
    await integer_half_test_generated_1();
    await integer_half_test_generated_2();
    await integer_half_test_generated_3();
    await integer_half_test_generated_4();
    await integer_half_test_generated_5();
    await integer_mod_test_generated_1();
    await integer_mod_test_generated_10();
    await integer_mod_test_generated_2();
    await integer_mod_test_generated_3();
    await integer_mod_test_generated_4();
    await integer_mod_test_generated_5();
    await integer_mod_test_generated_6();
    await integer_mod_test_generated_7();
    await integer_mod_test_generated_8();
    await integer_mod_test_generated_9();
    await js_identifier_is_test_1();
    await js_identifier_is_test_10();
    await js_identifier_is_test_2();
    await js_identifier_is_test_3();
    await js_identifier_is_test_4();
    await js_identifier_is_test_5();
    await js_identifier_is_test_6();
    await js_identifier_is_test_7();
    await js_identifier_is_test_8();
    await js_identifier_is_test_9();
    await js_identifier_is_test_generated_1();
    await js_identifier_is_test_generated_2();
    await js_identifier_is_test_generated_3();
    await js_identifier_is_test_generated_4();
    await js_identifier_is_test_generated_5();
    await js_identifier_sub_is_test_1();
    await js_identifier_sub_is_test_10();
    await js_identifier_sub_is_test_2();
    await js_identifier_sub_is_test_3();
    await js_identifier_sub_is_test_4();
    await js_identifier_sub_is_test_5();
    await js_identifier_sub_is_test_6();
    await js_identifier_sub_is_test_7();
    await js_identifier_sub_is_test_8();
    await js_identifier_sub_is_test_9();
    await js_identifier_sub_is_test_generated_1();
    await js_identifier_sub_is_test_generated_2();
    await js_identifier_sub_is_test_generated_3();
    await js_identifier_sub_is_test_generated_4();
    await js_identifier_sub_is_test_generated_5();
    await range_from_test_generated_1();
    await range_from_test_generated_10();
    await range_from_test_generated_2();
    await range_from_test_generated_3();
    await range_from_test_generated_4();
    await range_from_test_generated_5();
    await range_from_test_generated_6();
    await range_from_test_generated_7();
    await range_from_test_generated_8();
    await string_a_test_generated_1();
    await string_case_snake_to_pascal_test_generated_1();
    await string_case_snake_to_pascal_test_generated_2();
    await string_case_snake_to_pascal_test_generated_3();
    await string_case_snake_to_pascal_test_generated_4();
    await string_case_snake_to_pascal_test_generated_5();
    await string_case_upper_character_first_test_generated_1();
    await string_case_upper_character_first_test_generated_2();
    await string_case_upper_character_first_test_generated_3();
    await string_case_upper_character_first_test_generated_4();
    await string_case_upper_character_first_test_generated_5();
    await string_difference_apply_parse_test_1();
    await string_difference_apply_parse_test_2();
    await string_difference_apply_parse_test_3();
    await string_difference_apply_parse_test_4();
    await string_difference_apply_test_1();
    await string_difference_apply_test_10();
    await string_difference_apply_test_2();
    await string_difference_apply_test_3();
    await string_difference_apply_test_4();
    await string_difference_apply_test_5();
    await string_difference_apply_test_6();
    await string_difference_apply_test_7();
    await string_difference_apply_test_8();
    await string_difference_apply_test_9();
    await string_difference_get_external_test_generated_1();
    await string_difference_get_external_test_generated_10();
    await string_difference_get_external_test_generated_2();
    await string_difference_get_external_test_generated_3();
    await string_difference_get_external_test_generated_4();
    await string_difference_get_external_test_generated_5();
    await string_difference_get_external_test_generated_6();
    await string_difference_get_external_test_generated_7();
    await string_difference_get_external_test_generated_8();
    await string_difference_get_external_test_generated_9();
    await string_difference_get_test_1();
    await string_difference_get_test_10();
    await string_difference_get_test_11();
    await string_difference_get_test_12();
    await string_difference_get_test_13();
    await string_difference_get_test_14();
    await string_difference_get_test_15();
    await string_difference_get_test_16();
    await string_difference_get_test_17();
    await string_difference_get_test_18();
    await string_difference_get_test_19();
    await string_difference_get_test_2();
    await string_difference_get_test_20();
    await string_difference_get_test_21();
    await string_difference_get_test_22();
    await string_difference_get_test_23();
    await string_difference_get_test_3();
    await string_difference_get_test_4();
    await string_difference_get_test_5();
    await string_difference_get_test_6();
    await string_difference_get_test_7();
    await string_difference_get_test_8();
    await string_difference_get_test_9();
    await string_difference_tests_test_generated_1();
    await string_difference_tests_test_generated_10();
    await string_difference_tests_test_generated_2();
    await string_difference_tests_test_generated_3();
    await string_difference_tests_test_generated_4();
    await string_difference_tests_test_generated_5();
    await string_difference_tests_test_generated_6();
    await string_difference_tests_test_generated_7();
    await string_difference_tests_test_generated_8();
    await string_difference_tests_test_generated_9();
    await string_digit_is_test_1();
    await string_digit_is_test_10();
    await string_digit_is_test_11();
    await string_digit_is_test_12();
    await string_digit_is_test_2();
    await string_digit_is_test_3();
    await string_digit_is_test_4();
    await string_digit_is_test_5();
    await string_digit_is_test_6();
    await string_digit_is_test_7();
    await string_digit_is_test_8();
    await string_digit_is_test_9();
    await string_digit_is_test_generated_1();
    await string_digit_is_test_generated_2();
    await string_digit_is_test_generated_3();
    await string_digit_is_test_generated_4();
    await string_digit_is_test_generated_5();
    await string_empty_is_test_generated_1();
    await string_empty_is_test_generated_2();
    await string_empty_is_test_generated_3();
    await string_empty_is_test_generated_4();
    await string_empty_is_test_generated_5();
    await string_empty_not_is_test_generated_1();
    await string_empty_not_is_test_generated_2();
    await string_empty_not_is_test_generated_3();
    await string_empty_not_is_test_generated_4();
    await string_empty_not_is_test_generated_5();
    await string_ends_with_test_generated_1();
    await string_ends_with_test_generated_10();
    await string_ends_with_test_generated_2();
    await string_ends_with_test_generated_3();
    await string_ends_with_test_generated_4();
    await string_ends_with_test_generated_5();
    await string_ends_with_test_generated_6();
    await string_ends_with_test_generated_7();
    await string_ends_with_test_generated_8();
    await string_ends_with_test_generated_9();
    await string_equal_count_test_generated_1();
    await string_equal_count_test_generated_10();
    await string_equal_count_test_generated_2();
    await string_equal_count_test_generated_3();
    await string_equal_count_test_generated_4();
    await string_equal_count_test_generated_5();
    await string_equal_count_test_generated_6();
    await string_equal_count_test_generated_7();
    await string_equal_count_test_generated_8();
    await string_equal_count_test_generated_9();
    await string_equal_except_1_test_generated_1();
    await string_equal_except_1_test_generated_10();
    await string_equal_except_1_test_generated_2();
    await string_equal_except_1_test_generated_3();
    await string_equal_except_1_test_generated_4();
    await string_equal_except_1_test_generated_5();
    await string_equal_except_1_test_generated_6();
    await string_equal_except_1_test_generated_7();
    await string_equal_except_1_test_generated_8();
    await string_equal_except_1_test_generated_9();
    await string_function_tests_name_is_test_1();
    await string_function_tests_name_is_test_2();
    await string_function_tests_name_is_test_3();
    await string_function_tests_name_is_test_4();
    await string_function_tests_name_is_test_5();
    await string_function_tests_name_is_test_6();
    await string_function_tests_name_is_test_generated_1();
    await string_function_tests_name_is_test_generated_2();
    await string_function_tests_name_is_test_generated_3();
    await string_function_tests_name_is_test_generated_4();
    await string_function_tests_name_is_test_generated_5();
    await string_function_tests_sub_test_generated_1();
    await string_includes_test_generated_1();
    await string_includes_test_generated_10();
    await string_includes_test_generated_2();
    await string_includes_test_generated_3();
    await string_includes_test_generated_4();
    await string_includes_test_generated_5();
    await string_includes_test_generated_6();
    await string_includes_test_generated_7();
    await string_includes_test_generated_8();
    await string_includes_test_generated_9();
    await string_index_of_test_generated_1();
    await string_index_of_test_generated_10();
    await string_index_of_test_generated_2();
    await string_index_of_test_generated_4();
    await string_index_of_test_generated_5();
    await string_index_of_test_generated_6();
    await string_index_of_test_generated_8();
    await string_index_of_try_test_generated_1();
    await string_index_of_try_test_generated_10();
    await string_index_of_try_test_generated_2();
    await string_index_of_try_test_generated_3();
    await string_index_of_try_test_generated_4();
    await string_index_of_try_test_generated_5();
    await string_index_of_try_test_generated_6();
    await string_index_of_try_test_generated_7();
    await string_index_of_try_test_generated_8();
    await string_index_of_try_test_generated_9();
    await string_letter_digit_or_underscore_is_test_1();
    await string_letter_digit_or_underscore_is_test_2();
    await string_letter_digit_or_underscore_is_test_3();
    await string_letter_digit_or_underscore_is_test_4();
    await string_letter_digit_or_underscore_is_test_5();
    await string_letter_digit_or_underscore_is_test_6();
    await string_letter_digit_or_underscore_is_test_7();
    await string_letter_digit_or_underscore_is_test_generated_1();
    await string_letter_digit_or_underscore_is_test_generated_2();
    await string_letter_digit_or_underscore_is_test_generated_3();
    await string_letter_digit_or_underscore_is_test_generated_4();
    await string_letter_digit_or_underscore_is_test_generated_5();
    await string_letter_is_test_1();
    await string_letter_is_test_2();
    await string_letter_is_test_3();
    await string_letter_is_test_4();
    await string_letter_is_test_5();
    await string_letter_is_test_6();
    await string_letter_is_test_7();
    await string_letter_is_test_generated_1();
    await string_letter_is_test_generated_2();
    await string_letter_is_test_generated_3();
    await string_letter_is_test_generated_4();
    await string_letter_is_test_generated_5();
    await string_new_line_test_generated_1();
    await string_prefix_replace_test_generated_1();
    await string_prefix_replace_test_generated_10();
    await string_prefix_replace_test_generated_2();
    await string_prefix_replace_test_generated_3();
    await string_prefix_replace_test_generated_4();
    await string_prefix_replace_test_generated_5();
    await string_prefix_replace_test_generated_6();
    await string_prefix_replace_test_generated_7();
    await string_prefix_replace_test_generated_8();
    await string_prefix_replace_test_generated_9();
    await string_prefix_without_test_generated_1();
    await string_prefix_without_test_generated_10();
    await string_prefix_without_test_generated_2();
    await string_prefix_without_test_generated_3();
    await string_prefix_without_test_generated_4();
    await string_prefix_without_test_generated_5();
    await string_prefix_without_test_generated_6();
    await string_prefix_without_test_generated_7();
    await string_prefix_without_test_generated_8();
    await string_prefix_without_test_generated_9();
    await string_remove_at_test_generated_1();
    await string_remove_at_test_generated_2();
    await string_remove_at_test_generated_3();
    await string_remove_at_test_generated_4();
    await string_remove_at_test_generated_8();
    await string_remove_at_test_generated_9();
    await string_repeat_is_test_generated_1();
    await string_repeat_is_test_generated_2();
    await string_repeat_is_test_generated_3();
    await string_repeat_is_test_generated_4();
    await string_repeat_is_test_generated_5();
    await string_replace_test_generated_1();
    await string_replace_test_generated_10();
    await string_replace_test_generated_2();
    await string_replace_test_generated_3();
    await string_replace_test_generated_4();
    await string_replace_test_generated_5();
    await string_replace_test_generated_6();
    await string_replace_test_generated_7();
    await string_replace_test_generated_8();
    await string_replace_test_generated_9();
    await string_set_test_generated_1();
    await string_set_test_generated_10();
    await string_set_test_generated_2();
    await string_set_test_generated_3();
    await string_set_test_generated_4();
    await string_similar_test_generated_1();
    await string_similar_test_generated_10();
    await string_similar_test_generated_11();
    await string_similar_test_generated_12();
    await string_similar_test_generated_13();
    await string_similar_test_generated_14();
    await string_similar_test_generated_15();
    await string_similar_test_generated_16();
    await string_similar_test_generated_17();
    await string_similar_test_generated_18();
    await string_similar_test_generated_19();
    await string_similar_test_generated_2();
    await string_similar_test_generated_20();
    await string_similar_test_generated_3();
    await string_similar_test_generated_4();
    await string_similar_test_generated_5();
    await string_similar_test_generated_6();
    await string_similar_test_generated_7();
    await string_similar_test_generated_8();
    await string_similar_test_generated_9();
    await string_skip_test_generated_1();
    await string_skip_test_generated_10();
    await string_skip_test_generated_2();
    await string_skip_test_generated_3();
    await string_skip_test_generated_4();
    await string_skip_test_generated_5();
    await string_skip_test_generated_6();
    await string_skip_test_generated_7();
    await string_skip_test_generated_8();
    await string_skip_test_generated_9();
    await string_split_test_generated_1();
    await string_split_test_generated_10();
    await string_split_test_generated_2();
    await string_split_test_generated_3();
    await string_split_test_generated_4();
    await string_split_test_generated_5();
    await string_split_test_generated_6();
    await string_split_test_generated_7();
    await string_split_test_generated_8();
    await string_split_test_generated_9();
    await string_starts_with_test_generated_1();
    await string_starts_with_test_generated_10();
    await string_starts_with_test_generated_2();
    await string_starts_with_test_generated_3();
    await string_starts_with_test_generated_4();
    await string_starts_with_test_generated_5();
    await string_starts_with_test_generated_6();
    await string_starts_with_test_generated_7();
    await string_starts_with_test_generated_8();
    await string_starts_with_test_generated_9();
    await string_sub_max_2_test_generated_1();
    await string_sub_max_2_test_generated_10();
    await string_sub_max_2_test_generated_2();
    await string_sub_max_2_test_generated_3();
    await string_sub_max_2_test_generated_4();
    await string_sub_max_2_test_generated_5();
    await string_sub_max_2_test_generated_6();
    await string_sub_max_2_test_generated_7();
    await string_sub_max_2_test_generated_8();
    await string_sub_max_2_test_generated_9();
    await string_sub_max_3_test_generated_1();
    await string_sub_max_3_test_generated_10();
    await string_sub_max_3_test_generated_2();
    await string_sub_max_3_test_generated_3();
    await string_sub_max_3_test_generated_4();
    await string_sub_max_3_test_generated_5();
    await string_sub_max_3_test_generated_6();
    await string_sub_max_3_test_generated_7();
    await string_sub_max_test_generated_1();
    await string_sub_max_test_generated_10();
    await string_sub_max_test_generated_2();
    await string_sub_max_test_generated_3();
    await string_sub_max_test_generated_4();
    await string_sub_max_test_generated_5();
    await string_sub_max_test_generated_6();
    await string_sub_max_test_generated_7();
    await string_sub_max_test_generated_8();
    await string_sub_max_test_generated_9();
    await string_sub_test_generated_1();
    await string_sub_test_generated_10();
    await string_sub_test_generated_2();
    await string_sub_test_generated_3();
    await string_sub_test_generated_4();
    await string_sub_test_generated_5();
    await string_sub_test_generated_6();
    await string_sub_test_generated_7();
    await string_sub_test_generated_8();
    await string_sub_test_generated_9();
    await string_suffix_without_test_generated_1();
    await string_suffix_without_test_generated_10();
    await string_suffix_without_test_generated_2();
    await string_suffix_without_test_generated_3();
    await string_suffix_without_test_generated_4();
    await string_suffix_without_test_generated_5();
    await string_suffix_without_test_generated_6();
    await string_suffix_without_test_generated_7();
    await string_suffix_without_test_generated_8();
    await string_suffix_without_test_generated_9();
    await string_swap_test_generated_1();
    await string_swap_test_generated_2();
    await string_swap_test_generated_6();
    await string_to_list_test_generated_1();
    await string_to_list_test_generated_2();
    await string_to_list_test_generated_3();
    await string_to_list_test_generated_4();
    await string_to_list_test_generated_5();
    await string_to_tree_test_generated_1();
    await string_to_tree_test_generated_2();
    await string_to_tree_test_generated_3();
    await string_to_tree_test_generated_4();
    await string_to_tree_test_generated_5();
    await string_underscore_is_test_1();
    await string_underscore_is_test_2();
    await string_underscore_is_test_3();
    await string_underscore_is_test_4();
    await string_underscore_is_test_5();
    await string_underscore_is_test_6();
    await string_underscore_is_test_7();
    await string_underscore_is_test_generated_1();
    await string_underscore_is_test_generated_2();
    await string_underscore_is_test_generated_3();
    await string_underscore_is_test_generated_4();
    await string_underscore_is_test_generated_5();
    log(string_combine('451', ' tests ran successfully'));
    metadata([]);
}